# Generated by Django 5.0.3 on 2025-03-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
    ]
