# Generated by Django 5.0.3 on 2025-04-27 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city'),
        ('mart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('despcription', models.CharField(max_length=300, verbose_name='Описание')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Новый'), (1, 'Б/У')], verbose_name='Тип')),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Изменено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Активное')),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Продано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='mart.category', verbose_name='Категория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='core.city', verbose_name='Город')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
