# Generated by Django 5.0.3 on 2025-04-30 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_alter_category_options_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sold_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата продажи'),
        ),
    ]
