# Generated by Django 5.0.3 on 2025-05-05 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
        ('mart', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='mart.ad', verbose_name='Объявление'),
        ),
    ]
